#!/usr/bin/env node
// build-areas.mjs — generate data/areas.json from the source CSVs.
// Source of truth: data/source/villages.csv + data/source/postcode-regions.csv
// Re-run whenever the source lists change:  node tools/build-areas.mjs
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const ROOT = fileURLToPath(new URL('..', import.meta.url)); // repo root, ends with /
const read = (p) => readFileSync(ROOT + p, 'utf8');
const parseCSV = (txt) => txt.trim().split(/\r?\n/).map((l) => l.split(','));
const slug = (s) => s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');

// postcode -> region info
const pcRows = parseCSV(read('data/source/postcode-regions.csv')).slice(1);
const pc = new Map();
for (const [, postcode, city, region, type] of pcRows) {
  pc.set(postcode, { city: city || '', region: region || '', type: type || '' });
}

const vRows = parseCSV(read('data/source/villages.csv')).slice(1);
const seen = new Set();
const areas = vRows
  .filter((r) => r.length >= 4 && r[2])
  .map(([county, town, village, postcode]) => {
    let id = `${slug(village)}-${slug(postcode)}`;
    if (seen.has(id)) { let i = 2; while (seen.has(`${id}-${i}`)) i++; id = `${id}-${i}`; }
    seen.add(id);
    const r = pc.get(postcode) || { city: '', region: '', type: '' };
    return {
      id,
      name: village,
      village,
      town,
      county,
      postcode,
      hubCity: r.city,
      regionDir: r.region,
      settlementType: r.type,
      subRegion: town,
      coords: null,
      overview: '',
      character: '',
      amenities: [],
      schools: [],
      transport: { commutes: [] },
      prices: {},
      thingsToDo: [],
      placesToEat: [],
      pros: [],
      cons: [],
      whoItSuits: [],
      houseTypeIds: [],
      images: [],
      sources: [],
      status: 'directory',
    };
  });

writeFileSync(`${ROOT}data/areas.json`, `${JSON.stringify(areas, null, 2)}\n`);

// Also (re)generate the human-readable docs/AREAS.md, grouped by county -> town.
const groups = {};
for (const a of areas) {
  (groups[a.county] ||= {});
  (groups[a.county][a.town] ||= []).push(a);
}
let md = '# AREAS — master location list\n\n';
md += 'Generated by `tools/build-areas.mjs` from `data/source/villages.csv` — **do not edit by hand**; '
   + 'edit the CSV (and `postcode-regions.csv`) then re-run `node tools/build-areas.mjs`. '
   + `Mirrors \`data/areas.json\`. **${areas.length}** locations. `
   + 'Status: `directory` (listed) → `drafted` → `complete`.\n';
for (const county of Object.keys(groups).sort()) {
  const total = Object.values(groups[county]).reduce((n, l) => n + l.length, 0);
  md += `\n## ${county} (${total})\n`;
  for (const town of Object.keys(groups[county]).sort()) {
    md += `\n### Near ${town} (${groups[county][town].length})\n`;
    md += '| Village | Postcode | id | Status |\n|---|---|---|---|\n';
    for (const a of groups[county][town]) md += `| ${a.village} | ${a.postcode} | ${a.id} | ${a.status} |\n`;
  }
}
writeFileSync(`${ROOT}docs/AREAS.md`, md);

const byCounty = areas.reduce((m, a) => ((m[a.county] = (m[a.county] || 0) + 1), m), {});
console.log(`Wrote ${areas.length} areas to data/areas.json and docs/AREAS.md`, byCounty);
